import { DataPenduduk } from "@/types/data";

export const dataPenduduk: DataPenduduk[] = [
  {
    id: 1,
    numberOfMale: 48,
    numberOfFemale: 45,
    numberOfHeadFamily: 31,
    numberOfFamilyMembers: 62,
    dusunId: 1,
    rtId: 1,
  },
  {
    id: 2,
    numberOfMale: 52,
    numberOfFemale: 49,
    numberOfHeadFamily: 28,
    numberOfFamilyMembers: 73,
    dusunId: 1,
    rtId: 2,
  },
  {
    id: 3,
    numberOfMale: 63,
    numberOfFemale: 49,
    numberOfHeadFamily: 38,
    numberOfFamilyMembers: 74,
    dusunId: 2,
    rtId: 3,
  },
  {
    id: 4,
    numberOfMale: 45,
    numberOfFemale: 46,
    numberOfHeadFamily: 26,
    numberOfFamilyMembers: 65,
    dusunId: 2,
    rtId: 4,
  },
  {
    id: 5,
    numberOfMale: 69,
    numberOfFemale: 52,
    numberOfHeadFamily: 36,
    numberOfFamilyMembers: 85,
    dusunId: 3,
    rtId: 5,
  },
  {
    id: 6,
    numberOfMale: 56,
    numberOfFemale: 42,
    numberOfHeadFamily: 32,
    numberOfFamilyMembers: 66,
    dusunId: 3,
    rtId: 6,
  },
  {
    id: 7,
    numberOfMale: 52,
    numberOfFemale: 47,
    numberOfHeadFamily: 30,
    numberOfFamilyMembers: 69,
    dusunId: 4,
    rtId: 7,
  },
  {
    id: 8,
    numberOfMale: 61,
    numberOfFemale: 55,
    numberOfHeadFamily: 33,
    numberOfFamilyMembers: 83,
    dusunId: 4,
    rtId: 8,
  },
  {
    id: 9,
    numberOfMale: 40,
    numberOfFemale: 29,
    numberOfHeadFamily: 22,
    numberOfFamilyMembers: 47,
    dusunId: 5,
    rtId: 9,
  },
  {
    id: 10,
    numberOfMale: 49,
    numberOfFemale: 45,
    numberOfHeadFamily: 29,
    numberOfFamilyMembers: 65,
    dusunId: 5,
    rtId: 10,
  },
];
